# Set width of screen in px
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# set dimensions and number of asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# set player values
PLAYER_RADIUS = 20

# SET MOVEMENT VARIABLES
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
